spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/corenetwork_config
  profiles:
    active: native

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: configserver